update: readme
mcrvaz/boleto-brasileiro-validator pull request #20
Opened 2021-09-20 19:36 UTC by leomaurodesenv

Atualização do link novo "Layout" de boletos de arrecação v6 (22/06/2020).

Comparei o layout v6 com o v5 (implementado neste código), aparentemente nenhuma mudança afeta este validator. As principais mudanças foram na forma de arrecadação e a forma de pagamento. Portanto, elas apenas adicionaram novos números (dígitos) e não alteraram a estrutura do boleto em si.

2021-09-22 16:01 UTC, mcrvaz requested changes

2021-09-22 16:01 UTC, mcrvaz commented on README.md
> +com Utilização do Código de Barras](https://portal.febraban.org.br/pagina/3166/33/pt-br/layour-arrecadacao)
Aqui seria bom que o link enviasse diretamente para o arquivo usado como referência pra implementação, senão podem adicionar novos documentos e não saberemos qual é o correto.
Link: (https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20ATUALIZADO.pdf)

2021-09-22 16:01 UTC, mcrvaz commented
Olá @leomaurodesenv , obrigado pela atualização! Deixei um comentário, assim que for corrigido já faço a a aprovação.

2021-09-24 00:32 UTC, leomaurodesenv commented on README.md
> +com Utilização do Código de Barras](https://portal.febraban.org.br/pagina/3166/33/pt-br/layour-arrecadacao)
Concordo contigo, correção feita.

2021-09-24 00:39 UTC, merged